# Generated by Django 3.0.3 on 2020-02-09 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apple', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(0), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
